openapi: 3.0.2
info:
  version: 1.0.0
  title: Tranware.com
  termsOfService: 'https://tranware.com/'
  contact:
    email: info@tranware.com
    url: 'https://tranware.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://webservices.tranware.net/NT/branding/logo.jpg'
  description: basic 
servers:
  - url: 'http://3.19.208.55:3003'
paths:
  /API/Trips/Create:
    $ref: paths/createTrip.yaml
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: api_key
