openapi: 3.0.2
info:
  version: 1.0.0
  title: Example.com
  termsOfService: 'https://example.com/terms/'
  contact:
    email: contact@example.com
    url: 'http://example.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://webservices.tranware.net/NT/branding/logo.jpg'
  description: basic configuration for TranAir2 MDTs
externalDocs:
  description: Find out how to create a GitHub repo for your OpenAPI definition.
  url: 'https://github.com/Rebilly/generator-openapi-repo'
tags:
  - name: Config
    description: configuration server
servers:
  - url: 'https://ta2config.tranware.net'
paths:
  /endpoint.php:
    $ref: paths/ta2config.yaml
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: api_key
